GET http://localhost:5000/api/auth/users/cikguharry@gmail.com

###

POST http://localhost:5000/api/auth/users
Content-Type: application/json

{ 
    "firstname": "Linda",
    "lastname": "Michael",
    "email": "linda@gmail.com",
    "password": "password",
    "organization_id": 1,
    "state": "Sabah",
    "country": "Malaysia"
}

###

POST http://localhost:5000/api/auth/signin
Content-Type: application/json

{"email":"mimin@gmail.com",
"password":"password",
"user":{
    "uid":3,
    "name":"Uchi Mong",
    "email":"lilah2@some.com",
    "isAdmin":"organizers",
    "password":"$2b$07$ky68GsxIIxtIAHMVZdI4rudZkyApFf8xDpMuUL7aaJX8dvixGTkKq"
    }
}s